name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
      - name: Build the Docker image
        id: buold
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          run: |
            uname -m
            docker build . --file Dockerfile --tag brok:$(date +%s)
